### ISSUE TITLE
Code?

### ISSUE THREAD

**Issue by j-dominguez9** [hundredblocks/transcription_demo#2]
Hi, is there any possible way to provide code for this example? The prompt obviously is the majority of the effort, but it's a little unclear how you chunked it and brought the html code back together. Presumably, there was a lot of repeated code. The prompt also is in the form of a base model, but the API is instruction-tuned, so it wouldn't make sense to end it with "Assistant: \<!DOCTYPE html>", is that correct? Also, was the transcript time-stamped? Where did you integrate the screenshot images? Were the screenshots of fixed time intervals or random throughout the video? Were the images time stamped? There's a lot of variability in the reproduction of this. Thanks!

**Comment by Yannael** [comment]
+1
I am trying to replicate this example, and it is unclear how images can be included. This looks like a prompt for a 'completion' api, but Claude 3 has a message API - https://docs.anthropic.com/claude/docs/vision . For example, what was in {desired_writing_style} ?

**Comment by j-dominguez9** [comment]
This is as close as I was able to get with the description provided and I did get an output that was decent, but it's still missing the screenshots. [Here](https://gitlab.com/j-dominguez9/transcription_demo/-/blob/main/blog_test.py?ref_type=heads)

I'm not entirely sure how to integrate those. I know the files in "frames" have a time stamp, but if the transcript is broken up by batches, are only the relevant timestamp screenshots entered into the prompt for that chunk? Also, are they supposed to be appended after the transcript? During?

**Comment by hundredblocks** [comment]
Thanks for the questions. Below are some answers inline:
> is there any possible way to provide code for this example?
I'm probably not going to have time to clean up the script I wrote to upload it here, but the only nuanced part is the transcript processing. Roughly:
- take a transcript with timestamps
- insert an image every N seconds with a name that had its path (e.g. `frames/image_123.jpeg`)
- chunk into C individual parts, to send to models in parallel

> it wouldn't make sense to end it with "Assistant: <!DOCTYPE html>", is that correct

You'll want to [prefill](https://docs.anthropic.com/claude/docs/prefill-claudes-response) Claude's response!
> was the transcript time-stamped?

yes
> what was in {desired_writing_style}

That points to [this image](https://github.com/hundredblocks/transcription_demo/blob/main/frames/example_output.jpg)

> if the transcript is broken up by batches, are only the relevant timestamp screenshots entered into the prompt for that chunk? 

Exactly.
> are they supposed to be appended after the transcript? During?

In the demo, I appended them during the transcript, but you may want to experiment

Hope this helps. This was put together as a quick demo so I doubt any of the choices described here are optimal, you should feel free to experiment
